# Generated by Django 4.2.5 on 2024-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_img', models.FileField(default=None, max_length=250, null=True, upload_to='skill/')),
            ],
        ),
    ]
